import type { CtaType, ThemeVibe } from "@/lib/design-spec";

/** Centralized copy for the app (no hardcoded strings in components). */
export const COPY = {
  HOME: {
    TITLE: "Landright",
    SUBTITLE:
      "Enter your business details and we'll generate four distinct landing pages. Pick one to export or generate four more similar to it.",
    LABELS: {
      COMPANY_NAME: "Company name",
      BUSINESS: "What does your business do? (tagline, value proposition…)",
      SKILLS: "What are your skills or niches?",
      CTA: "CTAs (add at least one; each needs a link)",
    },
    PLACEHOLDERS: {
      COMPANY_NAME: "e.g. Acme Inc",
      BUSINESS: "Tagline, what you do, value proposition…",
      SKILLS: "e.g. B2B SaaS, developer tools (comma-separated)",
    },
    CTA_ADD: "Add CTA",
    CTA_TYPE: "Type",
    CTA_LABEL: "Button/link label",
    CTA_URL: "Link URL (required, e.g. Calendly or signup page)",
    CTA_EMBED_CALENDLY: "Embed Calendly on page (for Book a call)",
    CTA_OPTIONS: {
      button: "Button (e.g. sign up, download)",
      call: "Book a call",
      trial: "Start trial / get access",
      contact_form: "Contact us (form on page)",
      contact_mailto: "Contact us (mailto link)",
    } as Record<CtaType, string>,
    CTA_CONTACT_EMAIL: "Your email (page owner — where visitors’ inquiries go)",
    SOCIALS: "Social links (optional)",
    SOCIAL_TWITTER: "Twitter / X",
    SOCIAL_LINKEDIN: "LinkedIn",
    SOCIAL_INSTAGRAM: "Instagram",
    SOCIAL_YOUTUBE: "YouTube",
    SOCIAL_GITHUB: "GitHub",
    LEGAL: "Legal pages (optional)",
    PRIVACY_URL: "Privacy policy URL",
    TERMS_URL: "Terms & conditions URL",
    SECURITY_URL: "Security URL",
    CONTINUE: "Continue",
    SUBMIT: "Generate landing pages",
    INSPIRATION_SCANNING: "Scanning inspiration…",
    RETRY_INSPIRATION: "Retry scan",
    WAIT_INSPIRATION:
      "Wait until inspiration finishes scanning, remove the screenshot, or retry after fixing the error.",
    SUBMIT_COOLDOWN: (seconds: number) => `Please wait ${seconds}s before generating again.`,
    COLOR_SCHEME: "Color scheme",
    COLOR_PRESETS: {
      neutral: "Neutral (grays)",
      warm: "Warm (amber/stone)",
      cool: "Cool (slate/blue)",
      dark: "Dark background",
      light: "Light background",
      brand: "Brand (use custom colors below)",
    } as Record<string, string>,
    COLOR_PRIMARY: "Primary (hex or name)",
    COLOR_SECONDARY: "Secondary",
    COLOR_BACKGROUND: "Background",
    COLOR_TEXT: "Text color",
    THEME: "Theme / vibe",
    THEME_OPTIONS: {
      minimal: "Minimal",
      editorial: "Editorial",
      bold: "Bold",
    } as Record<ThemeVibe, string>,
    REFERENCE_SITES: "Sites whose layout you like (URLs or describe, e.g. clean SaaS like Linear)",
  },
  PROMPTS: {
    TITLE: "Choose a style",
    SUBTITLE: "Pick one predefined prompt. This keeps generation consistent and saves tokens.",
    BACK: "Back to questions",
  },
  GENERATE: {
    BRAND: "Landright",
    NEW_SESSION: "New session",
    LOADING: "Generating variants…",
    ESTIMATED_TIME: "Estimated time: 3–5 minutes",
    LOADING_STEPS: [
      "Writing your design brief…",
      "Choosing color palettes and type…",
      "Generating variant 1 of 4…",
      "Drafting headlines and CTAs…",
      "Generating variant 2 of 4…",
      "Laying out sections…",
      "Generating variant 3 of 4…",
      "Adding social proof and trust…",
      "Generating variant 4 of 4…",
      "Running quality check…",
      "Polishing copy and spacing…",
      "Almost there…",
      "Checking responsiveness…",
      "Applying your brand voice…",
      "One moment…",
      "Fixing the last details…",
      "Building your variants…",
      "Tailwind + React, coming up…",
      "Design system locked in…",
      "Synthesizing four directions…",
    ],
    ERROR_RETRY: "Something went wrong. Check your API key and try again.",
    ERROR_RATE_LIMIT: "Too many requests. Please wait a moment and retry.",
    ERROR_JSON: "The model didn't return valid JSON. Try again or increase max tokens.",
    RETRY: "Retry",
    PICK_ONE: "Pick one of the four variants.",
    VARIANT: (n: number) => `Variant ${n}`,
    PICK_THIS: "Pick this one",
    YOU_PICKED: (n: number) => `You picked variant ${n}. What next?`,
    SATISFIED: "I'm satisfied",
    BACK_TO_VARIANTS: "Back to variants",
    CHANGE_LABEL: "Or request changes (specific elements or whole design)",
    CHANGE_PLACEHOLDER: "e.g. Bigger CTA, add testimonial, different style…",
    REGENERATE: "Regenerate variants",
    REGENERATING: "Regenerating…",
    DONE_TITLE: "You're all set",
    DONE_SUBTITLE: "You chose your preferred variant. Start over to generate again.",
    GENERATE_AGAIN: "Generate again",
    GENERATE_FOUR_SIMILAR: "Generate 4 new similar to this",
    ROUND: (n: number) => `Round ${n}`,
    SEND_TO_AGENT: "Send 4 variants to agent for testing",
    AGENT_PANEL_TITLE: "Upload 4 variants for testing",
    AGENT_USE_CURRENT: "Use current 4 variants",
    AGENT_UPLOAD_FILES: "Or upload 4 files (TSX/HTML)",
    AGENT_SEND: "Send to agent",
    AGENT_SENDING: "Sending…",
    AGENT_SUCCESS: "Sent to agent successfully",
    AGENT_ERROR: "Failed to send to agent",
    PUSH_ALL_FOUR_TO_GITHUB: "Push all 4 to GitHub",
    PUSH_ALL_SENDING: "Pushing 4 variants…",
    PUSH_ALL_SUCCESS: "All 4 variants pushed to GitHub",
    PUSH_ALL_ERROR: "Failed to push variants to GitHub",
    PUSH_ALL_AGENT_NOT_CONFIGURED:
      "Sync agent not configured. Add SYNC_AGENT_URL to .env.local (e.g. http://localhost:4000) and start the GitHub agent (python-agent), then try again.",
    LAYER_NAME_LABEL: "Layer name (e.g. layer-1 or layer-20250112)",
    LAYER_NAME_PLACEHOLDER: "layer-1",
  },
  DASHBOARD: {
    TITLE: "Analytics dashboard",
    REPO_PLACEHOLDER: "owner/repo",
    REPO_LABEL: "Repo",
    REFRESH: "Refresh",
    AUTO_REFRESH: "Auto-refresh (30s)",
    KPI_TOTAL_CLICKS: "Total CTA Clicks",
    KPI_TOP_VARIANT: "Top Variant",
    KPI_VARIANTS_TRACKED: "Variants Tracked",
    KPI_AGENT_EVENTS: "Agent Events",
    PANEL_CTA_PERFORMANCE: "CTA Performance",
    PANEL_WIN_RATES: "Variant Win Rates",
    PANEL_STRUCTURE: "Session variants (structure)",
    PANEL_AGENT_LOG: "Agent Decision Log",
    EMPTY_ENTER_REPO: "Enter a repo (e.g. owner/name) and click Refresh to load analytics.",
    EMPTY_NO_VARIANTS: "Generate variants on the Generate page, then return here to see structure for that session.",
    EMPTY_NO_EVENTS: "No CTA or agent events yet for this repo.",
    HOME_LINK: "Dashboard →",
  },
  EXPORT: {
    BUTTON: "Export code & instructions",
    TITLE: "Export your landing page",
    COPY_TSX: "Copy TSX",
    COPY_HTML: "Copy HTML",
    COPIED: "Copied",
    DOWNLOAD_TSX: "Download page.tsx",
    DOWNLOAD_HTML: "Download index.html",
    PUSH_TO_GITHUB: "Push to GitHub",
    PUSH_SENDING: "Pushing…",
    PUSH_SUCCESS: "Pushed to GitHub successfully",
    PUSH_ERROR: "Failed to push to GitHub",
    FILE_PATH_LABEL: "File path in repo",
    COMMIT_MESSAGE_LABEL: "Commit message",
    INSTRUCTIONS_TITLE: "How to implement",
    BACK: "Back",
  },
} as const;
